export const SET_INTABLE_CARDS = 'SET_INTABLE_CARDS';
export const SET_COMPUTER_STATE = 'SET_COMPUTER_STATE'
export const SET_USER_STATE = 'SET_USER_STATE'
export const SET_COMP_COMMENT = 'SET_COMP_COMMENT'
export const SET_CLICKD_CARD = 'SET_CLICKD_CARD'
export const SET_CLICKED_USER_CARD = 'SET_CLICKED_USER_CARD'